"""
topics.py
--------------------------------
Centralized MQTT topic definitions for the Distributed Weather and Altitude Monitor project.

Structure:
    weather/
        data/<site>/<sensor_type>/<sensor_id>
        status/<site>/<sensor_type>/<sensor_id>
        control/
            all
            <site>/<sensor_type>/all
            <site>/<sensor_type>/<sensor_id>
        config/<site>/<sensor_type>/<sensor_id>
        alert/<site>/<sensor_type>/<sensor_id>

All topic components are lowercase strings without spaces.
"""

# ====== DATA TOPICS ======

def data_topic(site: str, sensor_type: str, sensor_id: str) -> str:
    """
    Telemetry data published by sensors.
    Example: weather/data/pyrenees/meteo/meteo-001
    """
    return f"weather/data/{site}/{sensor_type}/{sensor_id}"


# ====== STATUS (ONLINE/OFFLINE) ======

def status_topic(site: str, sensor_type: str, sensor_id: str) -> str:
    """
    Online/offline status of each sensor (used for LWT messages).
    Example: weather/status/pyrenees/meteo/meteo-001
    """
    return f"weather/status/{site}/{sensor_type}/{sensor_id}"


# ====== CONTROL COMMANDS (FROM MONITOR TO SENSORS) ======

CTRL_SEND_ALL = "weather/control/all"

def ctrl_group_topic(site: str, sensor_type: str) -> str:
    """
    Control broadcast to all sensors of a given type at one site.
    Example: weather/control/pyrenees/meteo/all
    """
    return f"weather/control/{site}/{sensor_type}/all"

def ctrl_one_topic(site: str, sensor_type: str, sensor_id: str) -> str:
    """
    Unicast control to a specific sensor.
    Example: weather/control/pyrenees/meteo/meteo-001
    """
    return f"weather/control/{site}/{sensor_type}/{sensor_id}"


# ====== CONFIGURATION ======

def config_topic(site: str, sensor_type: str, sensor_id: str) -> str:
    """
    Persistent configuration (thresholds, calibration...).
    Example: weather/config/pyrenees/meteo/meteo-001
    """
    return f"weather/config/{site}/{sensor_type}/{sensor_id}"


# ====== ALERTS ======

def alert_topic(site: str, sensor_type: str, sensor_id: str) -> str:
    """
    Alerts generated by sensors or monitor (e.g., low pressure).
    Example: weather/alert/pyrenees/meteo/meteo-001
    """
    return f"weather/alert/{site}/{sensor_type}/{sensor_id}"


# ====== BELIEFS (DAI - Distributed Intelligence) ======

def belief_topic(site: str, sensor_type: str, sensor_id: str) -> str:
    """
    Belief/opinion published by each sensor about local risk.
    Example: weather/belief/pyrenees/meteo/meteo-001
    """
    return f"weather/belief/{site}/{sensor_type}/{sensor_id}"

def belief_site_topic(site: str, sensor_type: str) -> str:
    """
    Subscribe to all beliefs from sensors in the same site.
    Example: weather/belief/pyrenees/meteo/#
    """
    return f"weather/belief/{site}/{sensor_type}/#"


# ====== FEEDBACK (Learning) ======

def feedback_topic(site: str, sensor_type: str, sensor_id: str) -> str:
    """
    Feedback from monitor to sensor for learning/adjustment.
    Example: weather/feedback/pyrenees/meteo/meteo-001
    """
    return f"weather/feedback/{site}/{sensor_type}/{sensor_id}"


# ====== CONTROL TOPICS (Monitor to Sensor) ======

def reject_topic(sensor_id: str) -> str:
    """
    Topic to reject a sensor connection (too many connected).
    Example: weather/control/reject/meteo-001
    """
    return f"weather/control/reject/{sensor_id}"

def assign_sector_topic(sensor_id: str) -> str:
    """
    Topic to assign a sector to a sensor.
    Example: weather/control/assign/meteo-001
    """
    return f"weather/control/assign/{sensor_id}"


# ====== WILDCARDS (for subscriptions) ======

DATA_ALL          = "weather/data/#"
STATUS_ALL        = "weather/status/#"
CONTROL_ALL       = "weather/control/#"
CONFIG_ALL        = "weather/config/#"
ALERT_ALL         = "weather/alert/#"
BELIEF_ALL        = "weather/belief/#"
FEEDBACK_ALL      = "weather/feedback/#"
